apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: nginx-pod-without-label
spec:
  containers:
  - image: nginx:1.19
    name: nginx-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
